name: Build Kernel & ISO

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar o Código
      uses: actions/checkout@v4

    - name: Instalar Ferramentas
      run: |
        sudo apt update
        sudo apt install -y nasm build-essential gcc-multilib g++-multilib xorriso grub-pc-bin

    - name: Compilar o Kernel e Gerar a ISO
      run: |
        # 1. Cria a estrutura de pastas necessária
        mkdir -p build iso/boot/grub

        # 2. Compila os arquivos de src/ salvando os .o dentro de build/
        nasm -f elf32 src/boot.asm -o build/boot.o
        g++ -m32 -c src/kernel.cpp -o build/kernel.o -ffreestanding -O2 -Wall -Wextra -fno-exceptions -fno-rtti

        # 3. Linka usando os arquivos que estao na pasta build/
        ld -m elf_i386 -T linker.ld build/boot.o build/kernel.o -o build/myos.bin

        # 4. Copia o binario para a estrutura da ISO
        cp build/myos.bin iso/boot/myos.bin

        # 5. Cria o arquivo grub.cfg dentro de iso/boot/grub/
        cat << 'EOF' > iso/boot/grub/grub.cfg
        set timeout=0
        set default=0

        menuentry "Sadistic Shadow OS" {
            multiboot /boot/myos.bin
            boot
        }
        EOF

        # 6. Gera a ISO final
        grub-mkrescue -o build/myos.iso iso

    - name: Disponibilizar a ISO para Download (Artifact)
      uses: actions/upload-artifact@v4
      with:
        name: myos-iso
        path: build/myos.iso



    - name: Instalar Ferramentas
      run: |
        sudo apt update
        sudo apt install -y nasm build-essential gcc-multilib g++-multilib xorriso grub-pc-bin